### ISSUE TITLE
Job-local documentation has wrong ini example

### ISSUE THREAD

**Issue by Fixmetal** [mcuadros/ofelia#104]
The file [jobs.md](https://github.com/mcuadros/ofelia/blob/master/docs/jobs.md#job-local) shows a wrong documentation in the [job-local ini-file example](https://github.com/mcuadros/ofelia/blob/master/docs/jobs.md#ini-file-example-2). It is:

> [job-run "touch-test-file"]
> schedule = @every 15s
> command = touch test.txt
> dir = /tmp/sandbox/

Based on README.md it should be (I guess):

> [**job-local** "touch-test-file"]
> schedule = @every 15s
> command = touch test.txt

I guess it's just a typo. Could you please check?

**Comment by Trane9991** [comment]
Yes. Seems like you are right.
Can you prepare a Pull Request for this? (If not, it is fine I can do change on my own) :)

**Comment by Fixmetal** [comment]
PR opened, let me know if fits. Thanks

**Comment by Trane9991** [comment]
Thanks!
