### ISSUE TITLE
Option to use a tcp connection instead of a socket to communicate with docker

### ISSUE THREAD

**Issue by grimneko** [mcuadros/ofelia#110]
What I miss is an option to have Ofelia communicate via tcp (like tcp://dockerproxy:2375) with the docker daemon in order to reduce the available commands to the bare minimum and so secure the whole setup a bit. I like to use [tecnativa/docker-proxy](https://github.com/Tecnativa/docker-socket-proxy) to keep all containers who need access to the docker socket as limited as possible to reduce the surface in case of a attack.

**Comment by Akruidenberg** [comment]
+1

**Comment by Akruidenberg** [comment]
add the env `DOCKER_HOST: tcp://example:2375` to your docker/docker compose. Let me know if it's working :)

**Comment by Trane9991** [comment]
Yup, @Akruidenberg is correct.

Ofelia uses [docker.NewClientFromEnv](https://pkg.go.dev/github.com/fsouza/go-dockerclient?tab=doc#NewClientFromEnv), which should support `DOCKER_HOST: tcp://example:2375`, from documentaion:

> NewClientFromEnv returns a Client instance ready for communication created from Docker's default logic for the environment variables DOCKER_HOST, DOCKER_TLS_VERIFY, DOCKER_CERT_PATH, and DOCKER_API_VERSION.

Please reopen the issue if you have further questions.
