### ISSUE TITLE
Feature Request: specifying volume mounts/binds

### ISSUE THREAD

**Issue by Gaibhne** [mcuadros/ofelia#111]
Especially the 'run once' mode seems somewhat crippled without the ability for the created container to read or write anything.

**Comment by Trane9991** [comment]
Yes, volumes/binds is an important feature that was requested many times.
I want to implement it, but I can't give you any ETA.
If you are willing to prepare PR with the implementation I will be happy to review it.

**Comment by roman-geraskin** [comment]
Hello. May be we could make some PR from this one: https://github.com/mcuadros/ofelia/commit/28e1b9dd273fd382197dc71fc39ca0d6eed48a0c

**Comment by Trane9991** [comment]
This is implemented. Please check https://github.com/mcuadros/ofelia/blob/master/docs/jobs.md#job-run for examples
