### ISSUE TITLE
Ofelia won't start on Raspberry pi 4

### ISSUE THREAD

**Issue by grglzrv** [mcuadros/ofelia#112]
Hello, 

I'm trying to start Ofelia on Raspberry Pi 4, but I got this error below:

`ofelia         | standard_init_linux.go:211: exec user process caused "exec format error"`

My OS is Raspberry Pi4 with ARCH `armv7l`

Maybe the solution is to build Ofelia image for ARCH `armv7l` 

if there is already built image for Raspberry Pi, could you please provide me a link, or provide me detailed steps how to build it by myself.

It would be very useful, if we have image for Raspberry Pi 4.

Looking forward to hearing from you.

All my best,
George

**Comment by grglzrv** [comment]
I've already built it by myself, image is pushed into Docker hub - lazarovg/ofelia:armv7

**Comment by mumrau** [comment]
Probably a "duplicate" of #77 though.

**Comment by GitSchorsch** [comment]
I'm running ofelia from 0xERROR's multiarch build. Works like a charm.

**Comment by Trane9991** [comment]
![Screen Shot 2021-03-18 at 12 29 17 PM](https://user-images.githubusercontent.com/9948629/111611911-9e6aec00-87e5-11eb-8c59-0fba350e1cb6.png)

done ✅
