### ISSUE TITLE
Ofelia seems to trigger rate limiting on docker hub

### ISSUE THREAD

**Issue by PiotrCzapla** [mcuadros/ofelia#135]
after having ofelia run a command every 5 sec (testing) that was using single  curl container my host was rate limited. 
it seems that ofelia tries to fetch a new version of the container on every run, each query seems to count toward rate limits on docker hub. 

any idea how to fix this?

here is what i'm getting right now on the host
Unable to find image 'ubuntu:latest' locally
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
See 'docker run --help'.

**Comment by PiotrCzapla** [comment]
Using pull = false doesn't seems to have any effects :(, it always says that the image was pulled.
I'm not sure if using local images does not trigger the rate limiting as if the pull option does not work ofelia will try to pull first then lookup the local image.
I'm using the latest docker version

**Comment by Trane9991** [comment]
Hey, what kind of job you are running? `job-run` I assume?

`pull = false` supposed to help according to the following code:
https://github.com/mcuadros/ofelia/blob/ee6490d6e312ffd57f58721cf9311d08cb5ed3e7/core/runjob.go#L41-L63

It has to look for an image locally, and if it is there, not to pull again.

**Comment by PiotrCzapla** [comment]
Yeah I’ve seen it. but it does not work, as the parameter seems to be
ignored. I set that in the config the when I look at job description it
says Pull:true
It can be simply replicated just run any job really with pull = false, and
save all jobs to disk to see the config.

**Comment by Trane9991** [comment]
You are correct, looks like usage of https://github.com/mcuadros/go-defaults changes the user-provided `false` value to the default `true`. Will look into the fix

**Comment by PiotrCzapla** [comment]
Awesome find,I wouldn't be able to figure that out. Thank you!
