### ISSUE TITLE
Impossible to get (error) logs

### ISSUE THREAD

**Issue by Gaibhne** [mcuadros/ofelia#141]
It seems to be impossible to get the output/errors/stderr from failed jobs, if anyone finds a way or a hack around it, please drop a line here, because I have attempted every combination of saving the output, mailing it, redirecting it to files and so on and nothing seems to work.

Some things I have tried that did not allow me to see the problem:

    ofelia.job-run.status-update.command: bash -c "mysql --defaults-extra-file=/credentials/my.cnf -N --execute=\"<some SQL statement that errors out \""

Error files are empty, docker logs are empty.

    ofelia.job-run.status-update.command: bash -c "mysql --defaults-extra-file=/credentials/my.cnf -N --execute=\"<some SQL statement that errors out \"" >> /logs/out.txt

File gets created, but is empty.

    ofelia.job-run.status-update.command: bash -c "mysql --defaults-extra-file=/credentials/my.cnf -N --execute=\"<some SQL statement that errors out \"" 2>&1 >> /logs/out.txt

File gets created, but is empty.

    ofelia.job-run.status-update.command: bash -c "mysql --defaults-extra-file=/credentials/my.cnf -N --execute=\"<some SQL statement that errors out \" 2>&1 >> /logs/out.txt"

File gets created, but is empty.

I have also tried a frankly hilarious amount of variations of escaping various parts of the command, but since the file gets created, I'm guessing no escaping is needed.

/logs is mounted correctly, of course (otherwise it couldn't create the file). Mails come with files that claim to have a size (370 bytes, always) but are actually empty. Log files saved on the disk are 0 bytes.

**Comment by alekseysavitskiy** [comment]
@Gaibhne try this variant:
```
 ofelia.job-run.status-update.command: bash -c "mysql --defaults-extra-file=/credentials/my.cnf -N --execute=\"<some SQL statement that errors out \" 2>&1"

**Comment by Trane9991** [comment]
Hey @Gaibhne, thanks, there is an issue that logs are not being retrieved from the failed container. Thanks for reporting this.
Will push the fix soon.

**Comment by Gaibhne** [comment]
Thanks!
