### ISSUE TITLE
Docker image uses a no longer supported go version

### ISSUE THREAD

**Issue by christianbur** [mcuadros/ofelia#150]
Hello, the ofelia docker image was just integrated into [mailcow](https://github.com/mailcow/mailcow-dockerized/commit/971434ddd354a87208cbee87d399fc66be3e94ff#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L564). 
Unfortunately, the current docker image (mcuadros/ofelia:latest) includes outdated software.

- mcuadros/ofelia:latest -> [FROM golang:1.13.10-alpine](https://github.com/mcuadros/ofelia/blob/5286bee5ab3d18cd55ca214e7c5dea2943f69127/Dockerfile#L1) -> [The version is out of support](https://endoflife.date/go) 
- [alpine:3.11 ](https://github.com/mcuadros/ofelia/blob/5286bee5ab3d18cd55ca214e7c5dea2943f69127/Dockerfile#L10) could also be upgraded to alpine:3.13. 

An updating would be very nice, because otherwise Ofelia does not match to the description "Ofelia is a modern ... " :-)

**Comment by andryyy** [comment]
Hi, any update? :) @mcuadros Do you see a problem updating to the latest version? I can run a test if you like.

**Comment by Trane9991** [comment]
Published new version https://github.com/mcuadros/ofelia/releases/tag/v0.3.5
