### ISSUE TITLE
which kind of `command` can I use ?

### ISSUE THREAD

**Issue by haoliang-gao** [mcuadros/ofelia#16]
I run ofelia in a container, and just have configures like this:

```
[job-local "a-job"]
schedule = @every 10s
command = date >> /tmp/date.log
```
traced log using `docker log`:
```
2016/12/29 05:44:37 scheduler.go:124 ▶ NOTICE work-in-workstation - Job finished "30b8dc1f1104" in "116.700666ms", failed: false, skipped: false, error: none
```
But, I do not find the `/tmp/date.log` in the container.

If I change the move the command to a shell script something like `/tmp/run.sh`,
 then change the config command line to /tmp/run.sh, It works fine.

The doc or readme have no description about the `command`,
Would you give out some usages ?

**Comment by mcuadros** [comment]
If you wish to make redirects you should use `bash -c "date >> /tmp/date.log"`, the command is not being executed inside of a shell

**Comment by haoliang-gao** [comment]
Ah, I see.
I just confused with `shell built-in command` and  `linux command`.
Thank you!

**Comment by C-Duv** [comment]
In my case, the following works (the `/tmp/hello.txt` gets created in the *somecontainer* container)  :
```Ini
[job-exec "test-in-running"]
schedule = "*/5 * * * * *"
container = somecontainer
command = touch /tmp/hello.txt
```

But not any following `command` line:
* `command = bash -c "date >> /tmp/date.log"`
* `command = bash -c "echo $(date --utc +'%F_%H-%M-%S_%Z'): hello from $(hostname) >> /tmp/hello.txt"`

No file gets created in `/tmp` in the *somecontainer* container.

**Comment by jTd7bPLFb** [comment]
command = "bash -c 'date >>/tmp/test'"
