### ISSUE TITLE
Add option to config TLSConfig.InsecureSkipVerify allowing to use self signed certs for mail server

### ISSUE THREAD

**Issue by marcelhorner** [mcuadros/ofelia#193]
I had to setup the InsecureSkipVerify on TLSConfig to be able to send emails on my test server because the mail server has self-signed certificate.

I've created a custom docker image for that and I have the code on my local git branch.

If you think this is a good config option to add to Ofelia, I can create the PR to the main branch if someone can give me access to create new branch and open PR on the repository.

I've made the following changes:
- `middlewares/mail.go`: added import to `crypto/tls` and created the `SMTPTLSSkipVerify` on `MailConfig` struct, which value comes from `smtp-tls-skip-verify` config. The value of `smtp-tls-skip-verify` config is tested at `sendMail()` method, and when true it sets `TLSConfig.InsecureSkipVerify` to `true` for the `gomail PlainDialer`.
- `README.md`: added the description for the new config at `Logging > Options`: "`smtp-tls-skip-verify` - when `true` ignores certificate signed by unknown authority error."

Default value for `smtp-tls-skip-verify` config is `false`. When this config is omitted certificate signer is validated, the same way it is working now.

**Comment by marcelhorner** [comment]
Just finded out I can create a pull request from a forked repo.

Here it is:
https://github.com/mcuadros/ofelia/pull/194

**Comment by Trane9991** [comment]
PR #194 is merged, new version released https://github.com/mcuadros/ofelia/releases/tag/v0.3.7
