### ISSUE TITLE
Readme Installation

### ISSUE THREAD

**Issue by arnaudmm** [mcuadros/ofelia#22]
Hello,

I don't know if this is intentionally missing from the installation section, but I had to mount docker socket otherwise ofelia is complaning:
2017/01/30 13:39:25 scheduler.go:120 ▶ ERROR job-executed-on-running-container - Job finished "4b89cd11bf19" in "330.614µs", failed: true, skipped: false, error: error creating exec: Post http://unix.sock/containers/opendj/exec: dial unix /var/run/docker.sock: connect: no such file or directory

I fixed this with:

-v /var/run/docker.sock:/var/run/docker.sock

Any alternative? Thanks!

**Comment by JohannCR** [comment]
Ran into the same problem, and don't know how to apply that workraound in the DSM docker GUI...
Can someone describe what command to run in the container's terminal ? Thanks
