### ISSUE TITLE
Incorrect Lang

### ISSUE THREAD

**Issue by DaCaTr** [mcuadros/ofelia#241]
Hi, I've been trying to set the language used by the container to de_DE for a bit now and was wondering if this was an error on Ofelia's side or my configuration. The Language is the only Problem I'm having as the timezone seems to be set properly.

I've tried adding the localization packages manually in the dockerfile via apk add but to no avail. 
My Dockerfile currently looks like this: 

FROM mcuadros/ofelia:latest
RUN apk --no-cache add openssh-client sshpass curl
RUN apk add --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main glibc-langpack-de_DE

RUN cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime
RUN echo "Europe/Berlin" >  /etc/timezone

# set the default locale to de_DE.utf-8
#RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG de_DE.UTF-8
ENV LANGUAGE de_DE:de
ENV LC_ALL de_DE.UTF-8

----------------

I've also uncommented and commented every other line to see if the error are with them but it seems not. 
Tried to create an .env file as well with no change in language either...

Thanks in advance.

(edited for the link to be properly formated)

**Comment by TheDevMinerTV** [comment]
What _exactly_ do you want to achieve?
