### ISSUE TITLE
hub docker TYPO? v3.0.8

### ISSUE THREAD

**Issue by webysther** [mcuadros/ofelia#254]
I think is v0.3.8 right? https://hub.docker.com/r/mcuadros/ofelia/tags

**Comment by taraspos** [comment]
Yes, sorry, there was a typo in the release tag, that's  fixed now, but I don't have permission to remove the image from the docker hub unfortunately.

I'm planning to publish a new release soon, probably this weekend, so you could use that one.

**Comment by webysther** [comment]
No worries
