### ISSUE TITLE
job-local causes go panic, Can't schedule jobs

### ISSUE THREAD

**Issue by it9exm** [mcuadros/ofelia#256]
Basic setup very similar to README, here's what I'm getting instead of a scheduled job

```
2024-03-07T15:03:32.003Z  common.go:125 ▶ NOTICE [Job "test" (80f5240a21e3)] Started - 
2024/03/07 15:03:32 cron: panic running job: runtime error: index out of range [0] with length 0
goroutine 30 [running]:
github.com/robfig/cron.(*Cron).runWithRecovery.func1()
	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:161 +0x65
panic({0x906380?, 0xc000194030?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/mcuadros/ofelia/core.(*LocalJob).buildCommand(0xc0001a4140, 0xc00006c300)
	/go/src/github.com/mcuadros/ofelia/core/localjob.go:31 +0x248
github.com/mcuadros/ofelia/core.(*LocalJob).Run(0xc000186000?, 0x3?)
	/go/src/github.com/mcuadros/ofelia/core/localjob.go:21 +0x13
github.com/mcuadros/ofelia/core.(*Context).doNext(0xc00006c300)
	/go/src/github.com/mcuadros/ofelia/core/common.go:95 +0xca
github.com/mcuadros/ofelia/core.(*Context).Next(0xc00006c300)
	/go/src/github.com/mcuadros/ofelia/core/common.go:69 +0x18
github.com/mcuadros/ofelia/core.(*jobWrapper).Run(0xc00019e5d0)
	/go/src/github.com/mcuadros/ofelia/core/scheduler.go:94 +0x1a5
github.com/robfig/cron.(*Cron).runWithRecovery(0xc0000000c0?, {0x9fc880?, 0xc00019e5d0?})
	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:165 +0x53
created by github.com/robfig/cron.(*Cron).run in goroutine 20
	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:199 +0x779

```

**Comment by taraspos** [comment]
Could you please share the exact configuration so I could try to reproduce the problem?

**Comment by it9exm** [comment]
sure, here's the docker-compose file which I tried to spin up from a standalone docker install running inside an unprivileged LXC container (debian bookworm, running on proxmox)

version: '3' 

services:
 ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    depends_on:
      - traefik
    command: daemon --docker
    volumes:       
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.test.schedule: "@every 5s"
      ofelia.job.local.test.command: "env"

**Comment by taraspos** [comment]
@it9exm 

you have a typo in your label configurations, one label called:
- `ofelia.job-local.test.schedule`
but another is:
- `ofelia.job.local.test.command`, which is not valid.

Change it to `ofelia.job-local.test.command` and it will work fine.
But I agree, error message could be a bit more friendly :)

**Comment by it9exm** [comment]
Damn, I didn't even slightly realize the error in the second label no matter how many times I scanned through it.
Thank you, I think we can archive this.
