### ISSUE TITLE
Give env variables to container to execute job

### ISSUE THREAD

**Issue by omauger** [mcuadros/ofelia#28]
In configuration config.ini we can give only the image to execute a container but we need to give environment variables to start this container.

For example :
[job-run "job-executed-on-new-container"]
schedule = @hourly
image = ubuntu:latest
command = touch /tmp/example
environment = ENV1=example,ENV2=example2...

**Comment by cevanwells** [comment]
This is a pretty important feature in my opinion, are there architectural issues preventing its inclusion? Is it already possible using a different method?

**Comment by eugenekurasov** [comment]
Hi, Any update about this feature?

**Comment by salviof** [comment]
Any update?

**Comment by brianwhigham** [comment]
just found this project and this was my first question.  Seems like such an obvious need.  I think I'll have to use a cron container or keep looking.  Neat project, though.

**Comment by migutak** [comment]
did you find a way to provide -env variables to a new container?

**Comment by Trane9991** [comment]
Released: https://github.com/mcuadros/ofelia/releases/tag/v0.3.6

**Comment by rokcarl** [comment]
Cool, but this doesn't allow dynamic environment variables.

For example, I have a `.env` file with secrets (so it's also marked in `.gitignore`) that get populated to containers running with docker compose. I can't pass these values to containers running with ofelia unless I hard-code them in the INI config, which I won't do for security reasons.
