### ISSUE TITLE
Limit ofelia to execute jobs in own docker stack only?

### ISSUE THREAD

**Issue by microrache** [mcuadros/ofelia#284]
We run a docker-host running multiple stacks from multiple users. As I just added a new stack including ofelia, I noticed that this ofelia-container executed the job from a different stack which was already deployed on this host, which came with ofelia-labels (and an own ofelia-container). Is there a possibility to prevent multiple executions when ofelia is deployed multiple times to the same host? In other words, can I define a "job-whitelist" for one ofelia-container naming only the jobs this instance should be take care of? Or can I limit the "scope" of an ofelia-container to "jobs from this stack only"?

**Comment by taraspos** [comment]
Would this solve your problem?
- https://github.com/mcuadros/ofelia/pull/212

**Comment by microrache** [comment]
Yes, this is exactly I was looking for. Don't know I could have missed that, sorry.
