### ISSUE TITLE
Hide SMTPPassword in email report

### ISSUE THREAD

**Issue by giosava94** [mcuadros/ofelia#288]
Hello,

I'm using ofelia to run a job and send a report, via email, to multiple users when an error occurs. 
In the email there are 3 files. The `*.json` one contains the configuration variables and also the SMTPPassowrd of the account used to send the email.

This behavior is a security problem in our case. In fact we do not want to show to receivers the details of the sender (most of all its account password).
Is it possible to hide this value from the report?

Regards,
Giovanni

**Comment by taraspos** [comment]
Released in [v0.3.13](https://github.com/mcuadros/ofelia/releases/tag/v0.3.13)
