### ISSUE TITLE
Config.ini Documentation

### ISSUE THREAD

**Issue by andrewnk** [mcuadros/ofelia#37]
As I'm not sure of the config.ini syntax, how do I use the mail, save, and slack logging features? I don't see it clearly explained in the documentation. Could you provide a full example of a config.ini that uses the various forms of logging? Thanks!

**Comment by andrewnk** [comment]
Nevermind, I was able to figure it out. For anyone else that may come across this, it is just a matter of adding the type of logging you need to the top of your config.ini:

```
[global]
smtp-host = your-smtp-host
smtp-port = your-smpt-port
email-to = your-email-to
email-from = your-email-from
mail-only-on-error = true or false
save-folder = your-save-folder
save-only-on-error = true or false
slack-webhook = your-slack-webhook
slack-only-on-error = true or false
```

**Comment by vanehu** [comment]
no document for this 
and no comment 
it's so bad
