### ISSUE TITLE
Cannot build master

### ISSUE THREAD

**Issue by sdhnshu** [mcuadros/ofelia#39]
The build gets an error on the step 5/7

The command '/bin/sh -c go get -v ./...  && go install -v ./...  && rm -rf $GOPATH/src/' returned a non-zero code: 2

**Comment by AlekKras** [comment]
Can you post the full output?

**Comment by nikalaikina** [comment]
Have the same problem. I can run it but build fails.
Here is the output:
`Sending build context to Docker daemon  16.44MB
Step 1/7 : FROM golang:1.7
 ---> 225948c9a8b1
Step 2/7 : MAINTAINER Máximo Cuadros <mcuadros@gmail.com>
 ---> Using cache
 ---> 62a6bdf08cc3
Step 3/7 : ADD . ${GOPATH}/src/github.com/mcuadros/ofelia
 ---> f1ab1cba574d
Step 4/7 : WORKDIR ${GOPATH}/src/github.com/mcuadros/ofelia
Removing intermediate container e6fd2344cc1f
 ---> 7ed9c9351e86
Step 5/7 : RUN go get -v ./...  && go install -v ./...  && rm -rf $GOPATH/src/
 ---> Running in e52b1ec39dc3
github.com/jessevdk/go-flags (download)
github.com/fsouza/go-dockerclient (download)
github.com/docker/docker (download)
github.com/docker/go-units (download)
github.com/mcuadros/go-defaults (download)
github.com/gobs/args (download)
github.com/robfig/cron (download)
Fetching https://gopkg.in/gomail.v2?go-get=1
Parsing meta tags from https://gopkg.in/gomail.v2?go-get=1 (status code 200)
get "gopkg.in/gomail.v2": found meta tag main.metaImport{Prefix:"gopkg.in/gomail.v2", VCS:"git", RepoRoot:"https://gopkg.in/gomail.v2"} at https://gopkg.in/gomail.v2?go-get=1
gopkg.in/gomail.v2 (download)
github.com/op/go-logging (download)
Fetching https://gopkg.in/gcfg.v1?go-get=1
Parsing meta tags from https://gopkg.in/gcfg.v1?go-get=1 (status code 200)
get "gopkg.in/gcfg.v1": found meta tag main.metaImport{Prefix:"gopkg.in/gcfg.v1", VCS:"git", RepoRoot:"https://gopkg.in/gcfg.v1"} at https://gopkg.in/gcfg.v1?go-get=1
gopkg.in/gcfg.v1 (download)
Fetching https://gopkg.in/warnings.v0?go-get=1
Parsing meta tags from https://gopkg.in/warnings.v0?go-get=1 (status code 200)
get "gopkg.in/warnings.v0": found meta tag main.metaImport{Prefix:"gopkg.in/warnings.v0", VCS:"git", RepoRoot:"https://gopkg.in/warnings.v0"} at https://gopkg.in/warnings.v0?go-get=1
gopkg.in/warnings.v0 (download)
github.com/jessevdk/go-flags
github.com/docker/docker/vendor/github.com/opencontainers/go-digest
github.com/docker/docker/vendor/github.com/opencontainers/image-spec/specs-go
github.com/docker/docker/vendor/github.com/opencontainers/image-spec/specs-go/v1
github.com/docker/docker/api/types/registry
github.com/docker/docker/api/types/blkiodev
github.com/docker/docker/api/types/mount
github.com/docker/docker/api/types/strslice
github.com/docker/docker/vendor/github.com/docker/go-connections/nat
github.com/docker/docker/vendor/github.com/docker/go-units
github.com/docker/docker/api/types/container
github.com/docker/docker/api/types/network
github.com/docker/docker/vendor/github.com/gogo/protobuf/proto
github.com/docker/docker/api/types/versions
github.com/docker/docker/api/types/filters
github.com/docker/docker/vendor/golang.org/x/sys/unix
github.com/docker/docker/vendor/golang.org/x/crypto/ssh/terminal
github.com/docker/docker/vendor/github.com/sirupsen/logrus
github.com/docker/docker/api/types/swarm/runtime
github.com/docker/docker/vendor/github.com/docker/libnetwork/ipamutils
github.com/docker/docker/vendor/github.com/pkg/errors
github.com/docker/docker/api/types/swarm
github.com/docker/docker/vendor/archive/tar
github.com/docker/docker/api/types
github.com/docker/docker/opts
github.com/docker/docker/pkg/fileutils
github.com/docker/docker/vendor/github.com/containerd/continuity/pathdriver
github.com/docker/docker/pkg/mount
github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/user
# github.com/docker/docker/pkg/mount
../../docker/docker/pkg/mount/mount.go:109: undefined: sort.Slice
github.com/docker/docker/pkg/ioutils
github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/system
github.com/docker/docker/pkg/pools
github.com/docker/docker/vendor/github.com/Nvveen/Gotty
github.com/docker/docker/pkg/term
github.com/docker/docker/pkg/jsonmessage
github.com/docker/docker/pkg/stdcopy
github.com/docker/go-units
github.com/mcuadros/go-defaults
github.com/gobs/args
github.com/robfig/cron
gopkg.in/gomail.v2
github.com/op/go-logging
gopkg.in/gcfg.v1/token
gopkg.in/gcfg.v1/types
gopkg.in/gcfg.v1/scanner
gopkg.in/warnings.v0
gopkg.in/gcfg.v1
The command '/bin/sh -c go get -v ./...  && go install -v ./...  && rm -rf $GOPATH/src/' returned a non-zero code: 2
`

**Comment by technoe** [comment]
I get exactly the same error.

**Comment by technoe** [comment]
Set the golang version to 1.9 and rebuild.

**Comment by Trane9991** [comment]
Should be resolved now
