### ISSUE TITLE
Run from Local Image?

### ISSUE THREAD

**Issue by jjorissen52** [mcuadros/ofelia#40]
I have built an image locally `local/manage_uploads:v1` and it seems like it's not being found. 

```
[job-run "hello-world"]
schedule = */1 * * * *
image = local/manage_uploads:v1
command =  echo "hello world!"
```

When I start ofelia with the above configuration, I get:

```
task_scheduler01  | 2018/04/16 21:17:52 scheduler.go:103 ▶ DEBUG hello-world - Job started "0c3c7368fa4d" - "echo hello world!"
task_scheduler01  | 2018/04/16 21:17:52 scheduler.go:120 ▶ ERROR hello-world - Job finished "0c3c7368fa4d" in "586.370188ms", failed: true, skipped: false, error: error pulling image "local/manage_uploads:v1": API error (404): {"message":"pull access denied for local/manage_uploads, repository does not exist or may require 'docker login'"}
```
Is there a way for me to allow ofelia to use a local image?

**Comment by AlekKras** [comment]
Have you logged in to docker?

**Comment by jjorissen52** [comment]
I don't have a local repository. Thanks for taking a look, but I have switched to another solution that is simpler for my current setup.

**Comment by nekar93** [comment]
hi @jjorissen52, what is the "another solution"?

**Comment by Trane9991** [comment]
This is supported now, see f8bcd2caccea9cd20cec059fc4482c3dd9e17f5b
