### ISSUE TITLE
How to run a local image

### ISSUE THREAD

**Issue by Fohlen** [mcuadros/ofelia#55]
Suppose I built a local image like this

```
docker build -t "myimage:local" .
```

It seems I can't run such an image via Ofelia, e.g

```
[job-run "fetch_sources"]
schedule = @hourly
image = myimage:local
command = mycommand
```

This will throw the issue: 
```
2018/10/09 15:53:45 scheduler.go:120 ▶ ERROR mycommand - Job finished "fff139bda4de" in "1.816653626s", failed: true, skipped: false, error: error pulling image "myimage:local": API error (404): pull access denied for myimage, repository does not exist or may require 'docker login'
```

**Comment by yuklia** [comment]
@Fohlen try 
1 to push image to registry
2 docker login ...
3 docker run ofelia ...

**Comment by czlvjin** [comment]
> That is an unsatisfying solution indeed. Why doesn't it use `docker run -it` anyways?

+1

**Comment by auryn31** [comment]
is there a way to use local images? or private repos? 

if I link the local config 
/Users/<username>/.docker/config.json:/config.json

I still geht an permission denied
