### ISSUE TITLE
is this repository still active?

### ISSUE THREAD

**Issue by eleaner** [mcuadros/ofelia#66]
There is a raft of questions and nobody seems to be answering them e.g. #21

**Comment by hongkongkiwi** [comment]
I can't comment on authors code writing (last commit was 10 months ago), but generally the questiosn are more like doing stuff in docker itself (run docker from docker, pass in credentials or mounted volumes, private auth of containers etc). So it appears there are not many actual bug reports outstanding, just general howto questions.

**Comment by Trane9991** [comment]
I made a fork, implemented some additional features I need (reading configurations from the docker labels). 
I could send a PR, but I doubt it will be merged.
My fork also has all the pending PRs: #48  #49 #59 

https://github.com/Trane9991/ofelia.
Technically, I could create a new repo and maintain it.

**Comment by djpbessems** [comment]
Seeing as there doesn't really seem to be any similar tool for scheduling jobs within a docker-infrastructure, I'm hoping Ofelia will remain maintained (if only for the fact that mcuadros' dockerimage on dockerhub is based on an outdated golang image).

I've forked Trane's repo for now to base my CI on (https://hub.docker.com/r/djpbessems/ofelia)

**Comment by hiphamster** [comment]
Is it possible to specify docker run options inside config.ini? It would be great to be able to mount volumes on the run or build an image with something like 'context'

**Comment by hiphamster** [comment]
Ofelia does not find my local image - i get 'error pulling image "docker_panda_python": API  error (404) ...."
[job-run "service-executed-on-new-container"]
image = docker_panda_python 

docker_panda_python image in fact exists.

**Comment by djpbessems** [comment]
As far as I can determine, Ofelia does not look at your local images, it retrieves them from a registry; so you would have to use a fully qualified name as it is available on dockerhub (or another registry).

For example: I have 3 images on my dockerhub account (https://hub.docker.com/u/djpbessems/): if I wanted to use one of the images on there, I would use `image = djpbessems/traefik-windows` instead of just `image = traefik-windows`

**Comment by hiphamster** [comment]
@djpbessems Thanks for reply. I'll create a separate issue for my questions. In regards to docker.sock, ofelia does have access to it,  'job-exec' on an existing container works perfectly well.

**Comment by hiphamster** [comment]
Thanks Danny. I have changed my setup to use a running container for now.
I'll try with a hosted image in a bit.

**Comment by colthreepv** [comment]
@Trane9991 have you tried contacting @mcuadros to be upped as maintainer on this project?

When considering a tool to choose it's really critical to be able to rely on a maintained project

**Comment by mcuadros** [comment]
I open to let other people to maintain the project.

**Comment by Trane9991** [comment]
@mcuadros I'm a bit busy right now, but I was planning to maintain it.
How do you see the best way to do that?

**Comment by dominikkv** [comment]
@mcuadros please make it happen :-)

**Comment by kerphi** [comment]
@mcuadros did you opened ofelia to other motivated maintainers? for example: @Trane9991 ?

**Comment by mcuadros** [comment]
Hi @Trane9991 is just sent you an invitation for colaborate! thanks for caring

**Comment by Trane9991** [comment]
Thanks, @mcuadros!
Accepted it.

one more question, how is a push to the https://hub.docker.com/r/mcuadros/ofelia happening?
Is there are automatic build configured or you used to do this manually?

**Comment by mcuadros** [comment]
It's an automated build, so should be done in push

**Comment by kerphi** [comment]
@Trane9991 do you plan to merge the work you did on your own Ofelia fork?
It would be great!

**Comment by Trane9991** [comment]
Yup will do that!
However, there is a bit more work I want to do before merging like moving to `go mod`, removing `vendor` directory that I have in my fork, etc.

However, as far as I see automatic Docker Hub build is not triggered :( so merge of my fork will not update the docker image. @mcuadros any chance you can help me with that? I don't have permissions to the repo to fix it...

**Comment by kerphi** [comment]
@mcuadros @Trane9991 for docker hub auto build you could change the docker hub account to an organization account so you can give admin access to several user account easily.

**Comment by Trane9991** [comment]
My fork changes merged, however, build on Docker hub still doesn't work :(

**Comment by mcuadros** [comment]
Let me take a look

**Comment by mcuadros** [comment]
Fixed, was a token issue between GH and DockerHub + plus a go mod
support on the Dockerfile.

Now the latest tag contains the current master, and once you take a
new version will be build in DockerHub.

**Comment by Gaibhne** [comment]
@Trane9991 it looks like you abandoned maintaining this repository in favor of your own fork. Can you confirm that ? I'm just picking this up, and I'd rather not bet on the wrong horse.

**Comment by Trane9991** [comment]
> @Trane9991 it looks like you abandoned maintaining this repository in favor of your own fork. Can you confirm that ? I'm just picking this up, and I'd rather not bet on the wrong horse.

Nope. If you can check my fork on the Github, the last commit is Nov 2, 2019.

But I'm not doing active development on the repo as well. I'm trying my best to answer the questions in the issues when I have time. However, I'm not the original developer and I do not know codebase perfectly.
I'm also not going to pick up any major feature requests for now, since I do not have enough time for that.
But if you will prepare PR with the feature you need I will do my best to review and merge it.

Thanks.

**Comment by Gaibhne** [comment]
Yeah, my apologies. I looked at the commit dates wrong, and when I realized my mistake, I removed my comment - but apparently not fast enough for you to not see it ;)
