### ISSUE TITLE
Ofelia not finding local image, tries to pull, errors out 

### ISSUE THREAD

**Issue by hiphamster** [mcuadros/ofelia#67]
Ofelia does not find my local image - i get 'error pulling image "docker_panda_python": API error (404) ...."
[job-run "service-executed-on-new-container"]
image = docker_panda_python

docker_panda_python image in fact exists.

job-exec on an existing container works fine

**Comment by Trane9991** [comment]
This is supported now, see f8bcd2caccea9cd20cec059fc4482c3dd9e17f5b
