### ISSUE TITLE
Add option for job-exec to run job as specific user

### ISSUE THREAD

**Issue by klingac** [mcuadros/ofelia#69]
It is not possible to run job-exec inside container with other user than root. 
With bare [`docker exec` ](https://docs.docker.com/engine/reference/commandline/exec/) it is param `--user` or `-u`:
```
docker exec -u my_user my-container touch /tmp/example
```
Please add option to specify username woth job-exec, e.g. this:
```
[job-exec "job-executed-on-running-container"]
schedule = @hourly
container = my-container
command = touch /tmp/example
user = my_user
```

**Comment by JenswBE** [comment]
Seems this option was implemented from the beginning, just not documented. You can find a reference document in my repo (PR has been sent): https://github.com/JenswBE/ofelia/blob/master/docs/jobs.md

Please note, the docs are based on Trane9991's fork. Some features might only be available on his  fork.
