### ISSUE TITLE
/var/run/docker.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by johnny2678** [mcuadros/ofelia#7]
Tried my first cron yesterday:
```/var/run/docker.sock: connect: no such file or directory```... any tips??:

    2016/02/05 05:12:10 scheduler.go:34  NOTICE New job registered "job-executed-on-new-container" - "/mnt/docker/google-domains-ddns-updater/init.d/update-ddns start" - "@hourly"
    2016/02/05 05:12:10 scheduler.go:54  DEBUG Starting scheduler with 1 jobs
    2016/02/05 06:00:00 scheduler.go:103  DEBUG job-executed-on-new-container - Job started "a26af2b652b6" - "/mnt/docker/google-domains-ddns-updater/init.d/update-ddns start"
    2016/02/05 06:00:00 scheduler.go:120  ERROR job-executed-on-new-container - Job finished "a26af2b652b6" in "263.004s", failed: true, skipped: false, error: error pulling image "jh/ubuntu-cron": dial unix /var/run/docker.sock: connect: no such file or directory

`config.ini` looks like this:

    [job-run "job-executed-on-new-container"]
    schedule = @hourly
    image = jh/ubuntu-cron
    command = /mnt/docker/google-domains-ddns-updater/init.d/update-ddns start

edit: title clarified

**Comment by mcuadros** [comment]
sorry about this epic delay.

you need to setup the common env variables: `DOCKER_HOST`, `DOCKER_TLS_VERIFY`, and `DOCKER_CERT_PATH` as you do with Docker engine. If you want to connect ofelia to the unix socket you need to mount it as a volume in the docker container of ofelia.

**Comment by c0ze** [comment]
for future reference, you need to pass

```
-v /var/run/docker.sock:/var/run/docker.sock:ro
```

when you run ofelia.
