### ISSUE TITLE
Mount volumes?

### ISSUE THREAD

**Issue by J0s3f** [mcuadros/ofelia#70]
Is there a way to run a new container but mount a volume there?

**Comment by funkymonkeymonk** [comment]
This is a problem I just came across setting up Ofelia as well. I was hoping to use Ofelia along with a job that has a hefty config file.

**Comment by cameronkerrnz** [comment]
This prevents me from using ofelia as I need to pass in a volume for secrets to my otherwise pretty simple integration task.

Similarly, environment variables would be useful.

**Comment by gjonespf** [comment]
Yeah, this is pretty much:
https://github.com/mcuadros/ofelia/issues/21#issuecomment-284768807
Which was closed as available on the run command.  I don't see anything in docs or source that would allow it however?  Perhaps adding ability to simply add unvalidated docker args might be worth looking at?

**Comment by Trane9991** [comment]
This is implemented. Please check https://github.com/mcuadros/ofelia/blob/master/docs/jobs.md#job-run for examples
