### ISSUE TITLE
Add more platforms and architectures

### ISSUE THREAD

**Issue by mariuszslabicki** [mcuadros/ofelia#77]
Hi

It would be nice if we can have ofelia image for other platforms (like arm32, arm64, etc.). Currently at dockerhub there is only linux/amd64.

Best regards
Mariusz

**Comment by guillerDev** [comment]
Hi, 
You can always build from your arm arch, just clone the project and `docker build . -t ofelia`

**Comment by praveendath92** [comment]
Any chance of publishing this to the docker registry? Or maybe instructions on how to build ourselves for these platforms?

**Comment by praveendath92** [comment]
Figured it out. Just had to use

```yaml 
build: https://github.com/mcuadros/ofelia.git
```

instead of 
```yaml
image: mcuadros/ofelia:latest
```

**Comment by Trane9991** [comment]
Hey there.
The build is done via Github Actions https://github.com/mcuadros/ofelia/blob/master/.github/workflows/docker.yml

If you can prepare PR with changes for builds on more platforms, I would be happy to review it.

**Comment by Trane9991** [comment]
![Screen Shot 2021-03-18 at 12 29 17 PM](https://user-images.githubusercontent.com/9948629/111611911-9e6aec00-87e5-11eb-8c59-0fba350e1cb6.png)

done ✅
