### ISSUE TITLE
Fails for me on local host and creating containers, questions about targeting

### ISSUE THREAD

**Issue by cloudlady911** [mcuadros/ofelia#8]
How can I target a container on another host?

I tried the option where it tries to create a container, but it fails to pull the image.
`5/6/2016 10:16:14 PM2016/05/07 05:16:14 [31mscheduler.go:120 ▶ ERROR[0m job-executed-on-new-container - Job finished "6c0daef33999" in "206.425µs", failed: true, skipped: false, error: error pulling image "ubuntu:latest": dial unix /var/run/docker.sock: connect: no such file or directory`

I tried the one where it target the local host using the touch /tmp/example but that failed as well.
`5/6/2016 10:25:35 PM2016/05/07 05:25:35 [32mscheduler.go:124 ▶ NOTICE[0m job-executed-on-current-host - Job finished "52a4541f03bc" in "1.226501ms", failed: false, skipped: false, error: none`

**Comment by mcuadros** [comment]
Can you provide your configuration file?

**Comment by gitlab-pano** [comment]
I am testing with your example:

[job-exec "job-executed-on-running-container"]
schedule = @every 60s
container = 39f869c273c6
command = touch /tmp/example

[job-run "job-executed-on-new-container"]
schedule = @every 90s
image = ubuntu:14.04.3
command = touch /tmp/example

[job-local "job-executed-on-current-host"]
schedule = @every 60s
command = touch /tmp/example

**Comment by tkntobfrk** [comment]
I think you need to update the run command. Docker run -d -v $path/docker.sock:$path/docker.sock -v ofeliapath:ofeliapath image.   Something like that should fix the new container error

**Comment by tkntobfrk** [comment]
docker run -d --name ofelia -v /var/run/docker.sock:/var/run/docker.sock -v /home/myid/ofelia:/etc/ofelia mcuadros/ofelia:latest

**Comment by cloudlady911** [comment]
Thanks, I will give that a try.
