### ISSUE TITLE
Tag docker images with the commit

### ISSUE THREAD

**Issue by gaastonsr** [mcuadros/ofelia#88]
Can you tag images with the commit being built too? https://hub.docker.com/r/mcuadros/ofelia/tags

**Comment by Trane9991** [comment]
@mcuadros could you please give me permissions for Docker Hub if possible?
So I could do better tagging of images, instead of always `latest` as currently done with the Automated Build on Docker Hub.

**Comment by mcuadros** [comment]
Sure let me know your docker hub handle.

**Comment by Trane9991** [comment]
Same as here, `trane9991` :)

**Comment by mcuadros** [comment]
Done

**Comment by olivierdalang** [comment]
Tagging with the commit isn't that useful as it's already possible to refer to the dockerhub hash to pin to an exact version.

The best would be to have some basic versioning, as asked on https://github.com/mcuadros/ofelia/issues/61
We don't need anything fancy, just new versions names anytime the release includes commit that could be backwards incompatible.

**Comment by gaastonsr** [comment]
Using a commit hash to tag the images is a massive improvement to know what commit was used to build the image, using semantic versioning or any type of versioning would be useful to know if there were breaking changes introduced but I wouldn't say that's very useful since new features aren't actively being worked on.

**Comment by olivierdalang** [comment]
Ok yes that can be useful indeed.
For semantic versionning, even if there's no active work on new features, this doesn't mean it's never going to be the case. Let's just call the current major version 1 (or 0 if you prefer), just so we aren't stuck with braking people stacks the day there's more changes.

**Comment by Trane9991** [comment]
Well, I do have permissions to push to the Docker hub as a collaborator but:
1. I don't have permissions to manage the GitHub repo to set "Secret Variables" to use GitHub Actions
2. I don't have permissions to manage the Travis build to set "Secret Variables" to use TravisCI
3. I'm not sure if using my personal account/token to push Docker hub is a good idea.

cc @mcuadros

**Comment by mcuadros** [comment]
The collaborators doesn't have any granularity so I can't give you access
to the secret.

I will migrate the test and artifacts builds to GitHub Actions. And I will
configure all the secrets.

**Comment by Trane9991** [comment]
@mcuadros sounds good. If you are too busy, you can also just set up the secrets, let me know their keys and I could the rest from there.

**Comment by mcuadros** [comment]
Solved

**Comment by gaastonsr** [comment]
Thanks!
