### ISSUE TITLE
Ofelia schedule doesn't work, even if the command works fine in original container?

### ISSUE THREAD

**Issue by gremo** [mcuadros/ofelia#92]
Here is my job:

```ini
[job-exec "MariaDB backup"]
schedule = @every 1m
container = mariadbserver_db
command = mysqldump -uroot -p`echo ${MYSQL_ROOT_PASSWORD}` --all-databases > /root/all-databases.sql
```

This command works **when I copy-paste in the `mariadbserver_db` container  shell**.

However it **doesn't work in ofelia**:

> common.go:121 ▶ NOTICE [Job "MariaDB backup" (76ef73b61d15)] Started - mysqldump -uroot -p`echo ${MYSQL_ROOT_PASSWORD}` --all-databases > /root/all-databases.sql
common.go:117 ▶ ERROR [Job "MariaDB backup" (76ef73b61d15)] Finished in "70.230501ms", failed: true, skipped: false, error: error non-zero exit code: 1

**Comment by Trane9991** [comment]
Hey @gremo 
could you try wrapping the command in the bash?

Basically: ```/bin/bash -c "mysqldump -uroot -p`echo ${MYSQL_ROOT_PASSWORD}` --all-databases > /root/all-databases.sql"```

**Comment by gremo** [comment]
So, the command isn't working because it's passaed as-is to `docker exec` commad?

**Comment by gremo** [comment]
Finally, got it working:

```ini
[job-exec "MariaDB backup"]
schedule = @every 1h
container = mariadbserver_db
command = sh -c \"mysqldump -uroot -p`echo ${MYSQL_ROOT_PASSWORD}` --routines --all-databases | gzip > /dumps/all-databases-$(date +%y%m%d%H%M).sql.gz\"
```

Quite unreadable. Is there a better way in your opinion?

**Comment by Trane9991** [comment]
> So, the command isn't working because it's passaed as-is to `docker exec` commad?

yes

> Quite unreadable. Is there a better way in your opinion?

I wouldn't name it very unreadable :) 
Looks like need for escaping quotes is the limitation on the side of `.ini` format.
Just tried with single quotes and it seems to be working fine:
```
[job-exec "Test"]
schedule = @every 1s
container = test
command = sh -c 'echo $(date +%y%m%d%H%M) | tee /tmp/test && cat /tmp/test'
```

**Comment by gremo** [comment]
Ok @Trane9991, really thank you for the help. Do you suggest to put the jon inside a script? If yes, were do I put the script?

**Comment by Trane9991** [comment]
Since this is `exec` job, the script would need to be present in the target container, which is pretty inconvenient, so I would probably keep it as is 🤷‍♂

**Comment by timdonovanuk** [comment]
Could this be better documented please? I'm trying to run a shell command also that has quotes in and its not entirely clear what I need to do to get it working in ofelia:

`find /photoprism/icloud -name '*' -type f -printf '%T@\t%p\0' | sort -rnz | tail -zn +2 | cut -zf2- | xargs -r0 mv -t /photoprism/import`

Some guidance on how commands like this should be placed in the .ini would be super helpful! Thank you.

**Comment by robflate** [comment]
@timdonovanuk Did you ever get this working? I'm trying to do a mysql dump of each separate database and can't work out how to escape it;

`command = /bin/bash -c "mysql -s -r -u root -pSecret -e 'show databases' | while read db; do mysqldump -u root -pSecret $db -r /backup/${db}.sql; [[ $? -eq 0 ]] && gzip /backup/${db}.sql; done"`
