### ISSUE TITLE
Unable to control time zone

### ISSUE THREAD

**Issue by qtplatypus** [mcuadros/ofelia#96]
After reviewing the documentation it isn't clear how one sets the time zone to be used.

**Comment by Trane9991** [comment]
Hey,
can you please explain what is your use-case?
Where do you need timezone to be set, on Ofelia itself or maybe in the scheduled container?

**Comment by qtplatypus** [comment]
the use case is that we are porting a non containerised  system that uses cron to a container based system using Ofelia to do the scheduled events.  In the cron based system we have the timezone set in the cron configuration in order to ensure that the times that the scheduled events happen are done in the correct time zone.

The place I need the timezone to be set is in the location ofelia uses to determine what time zone it is when deciding when to do a thing.

**Comment by Trane9991** [comment]
Scheduling is done by https://pkg.go.dev/github.com/robfig/cron.

Documentation says:

> **Time zones**
> All interpretation and scheduling is done in the machine's local time zone (as provided by the Go > time package (http://www.golang.org/pkg/time).
>
> Be aware that jobs scheduled during daylight-savings leap-ahead transitions will not be run!

So technically, setting env variable `TZ=Africa/Cairo` for the Ofelia container should do the trick, however, I didn't try that myself.  Can you try and let me know if that works?
