### ISSUE TITLE
[Question] How to run job once a day as soon as possible

### ISSUE THREAD

**Issue by 4n70w4** [mcuadros/ofelia#97]
Case: need run job only once a day in anytime but as soon as possible.

`@daily` not suitable, because it is depends on time, not the number of runs.
If for some reason the launch at 00:00 fails, then the `@daily` will not try to start it again.

I would like to have a guaranteed way to run the job only 1 time per day at any time.

**Comment by Trane9991** [comment]
Hey, @4n70w4 
I don't think that ofelia can satisfy such requirement (and normal corn as well), however, I think you could do a trick.

For example, you could create a job that runs every hour and leaves some marker on the file system like `touch marker-$(date +%F)` which will create file `marker-2020-04-17` then do the conditional start of the job based on that marker `test -f marker-$(date +%F) || echo "run job"`.

So the whole script could look like:
`export MARKER=marker-$(date +%F); test -f $MARKER || echo "run job" && touch $MARKER`
This will make sure that command runs only if the marker exists and will create one after a successful run and next time it will be executed when date changes - the next day.

Let me know if this approach works for you!

**Comment by 4n70w4** [comment]
Yes, this is a banal decision. I copy something similar from project to project.
In Ofelia it is written: `Ofelia aims to be a replacement for the old fashioned cron.`

I was expecting some new fashioned and more elegant solution. =)
